# Generated by Django 4.0.6 on 2022-10-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('primeiro_numero', models.IntegerField()),
                ('ultimo_numero', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loteria.jogos', verbose_name='jogos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Numero_sorteado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loteria.sorteio', verbose_name='sorteio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('jogo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loteria.jogos', verbose_name='jogos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
