# Generated by Django 4.0.6 on 2022-10-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0004_alter_numero_sorteado_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteio',
            name='numero',
            field=models.JSONField(default={'numero': []}),
        ),
        migrations.DeleteModel(
            name='Numero_sorteado',
        ),
    ]
