# Generated by Django 4.0.6 on 2022-10-28 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0005_sorteio_numero_delete_numero_sorteado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorteio',
            name='numero',
        ),
        migrations.CreateModel(
            name='Numero_sorteado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField()),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loteria.sorteio', verbose_name='sorteio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
