# Generated by Django 4.0.6 on 2022-10-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0006_remove_sorteio_numero_numero_sorteado'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='qt_n_sorteado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
