# Generated by Django 4.0.6 on 2022-11-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0007_jogos_qt_n_sorteado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteio',
            name='data_sorteio',
            field=models.DateField(default='2022-11-02'),
        ),
    ]
