# Generated by Django 4.0.6 on 2022-11-03 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0008_sorteio_data_sorteio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numero_apostados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField()),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loteria.sorteio', verbose_name='jogo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
